version: "3.8"
name: test-santex-challenge
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    depends_on:
      - "postgres"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  api:
    container_name: api
    image: node:16-alpine
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - ./src:/src
    working_dir: /src
    ports:
      - "4000:4000"
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: admin
    command: >
      sh -c "npm i && npm run serve"
